installEnvoyGateway: true

installPostgres: true

installCertManager: true

installKeycloak: true

installOpenTelemetry: true

installVault: true

autoInitVault: false

initialOrgId: ""

gatewayclassValues: {}

platformOrchestratorValues:
  messagingBootstrap:
    replicas: 3
  nats:
    config:
      cluster:
        enabled: true
        replicas: 3
      jetstream:
        fileStore:
          pvc:
            size: 10Gi
    statefulSet:
      merge:
        spec:
          template:
            spec:
              affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: app.kubernetes.io/name
                            operator: In
                            values:
                              - nats
                      topologyKey: kubernetes.io/hostname

vaultValues:
  injector:
    enabled: false
  server:
    standalone:
      enabled: false
    dataStorage:
      enabled: true
      size: 10Gi
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"

          telemetry {
            unauthenticated_metrics_access = true
          }
        }

        telemetry {
          disable_hostname = true
          prometheus_retention_time = "12h"
        }

openTelemetryOperatorValues:
  manager:
    createRbacPermissions: true
  admissionWebhooks:
    certManager:
      enabled: true
      issuerRef:
        name: selfsigned-cluster-issuer
        kind: ClusterIssuer
      duration: 8760h
      renewBefore: 360h

openTelemetryValues:
  collector:
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: "1"
        memory: 2Gi
